module.exports = [
  {
    user_id: 1,
    menu_item_id: 1,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 2,
    menu_item_id: 1,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 3,
    menu_item_id: 7,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 4,
    menu_item_id: 18,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 5,
    menu_item_id: 10,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 5,
    menu_item_id: 1,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 1,
    menu_item_id: 18,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 3,
    menu_item_id: 16,
    quantity: 1,
    modifications: null,
    paid: false,
  },
  {
    user_id: 3,
    menu_item_id: 3,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 5,
    menu_item_id: 12,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 7,
    menu_item_id: 19,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 7,
    menu_item_id: 12,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 6,
    menu_item_id: 7,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 5,
    menu_item_id: 10,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 4,
    menu_item_id: 1,
    quantity: 3,
    modifications: null,
    paid: false,
  },
  {
    user_id: 6,
    menu_item_id: 16,
    quantity: 1,
    modifications: null,
    paid: false,
  },
  {
    user_id: 3,
    menu_item_id: 3,
    quantity: 2,
    modifications: null,
    paid: false,
  },
  {
    user_id: 6,
    menu_item_id: 18,
    quantity: 3,
    modifications: null,
    paid: false,
  },
];
